name: Changed SvelteKit URLs

on:
  workflow_call:
    outputs:
      urlsChanged:
        description: 'The changed URLs'
        value: ${{ jobs.changed-urls-job.outputs.output1 }}

jobs:
  changed-urls-job:
    name: Changed URLs
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.changed-urls.outputs.urlsChanged }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          json: true
      - name: List all changed URLs
        id: changed-urls
        uses: actions/github-script@v6
        with:
          script: |
            const { default: getChangedPageUrls } = await import('${{ github.workspace }}/.github/scripts/detect-changed-urls.js')
            const urlsChanged = await getChangedPageUrls(
              'http://localhost',
              '${{ github.workspace }}',
              JSON.parse("${{ steps.changed-files.outputs.all_changed_files }}")
            );
            console.log('Changed URLs');
            urlsChanged.forEach(url => {
              console.log('URLs changed:', url);
            });
            core.setOutput("urlsChanged", urlsChanged.map(url => url + '.html').join('\n'));
