name: 'Lighthouse'

on:
  workflow_run:
    workflows: ['Deploy']
    types:
      - completed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lighthouse-production:
    name: Production
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Run Lighthouse on urls with lighthouserc-production
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: './.lighthouse/lighthouserc-production.cjs'
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
