name: PR verification

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ['main']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run check

  # Dependency Review Action
  #
  # This Action will scan dependency manifest files that change as part of a Pull Request, surfacing known-vulnerable versions of the packages declared or updated in the PR. Once installed, if the workflow run is marked as required, PRs introducing known-vulnerable packages will be blocked from merging.
  #
  # Source repository: https://github.com/actions/dependency-review-action
  # Public documentation: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
  dependency-review:
    name: Dependency review
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency review'
        uses: actions/dependency-review-action@v2

  changed-urls:
    name: Changed URLs
    uses: ./.github/workflows/changed-sveltekit-urls.yml

  comment-changed-urls:
    name: Post comment with changed URLs
    runs-on: ubuntu-latest
    needs: changed-urls
    steps:
      - name: Format message
        id: format-message
        uses: actions/github-script@v6
        with:
          script: |
            const urls = `${{ needs.changed-urls.outputs.urlsChanged }}`.split('\n');
            const message = [
              '# URLs updated',
              '',
              'URLs affected by changes in this PR',
              '',
              urls.map(url => `- ${url}`).join('\n'),
            ].join('\n');
            core.setOutput('message', message);
      - name: Comment changed URLs
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ${{ steps.format-message.outputs.message }}

  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    needs: changed-urls
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Run Lighthouse on urls with lighthouserc-pr
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            ${{ needs.changed-urls.outputs.urlsChanged }}
          configPath: './.lighthouse/lighthouserc-pr.json'
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
